--- #YAML:1.0
name:               Device-CableModem-Zoom5341
version:            1.01
abstract:           Read info from Zoom 5341 cable modem
author:
    - Matthew Fuller <fullermd@over-yonder.net>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
