---
abstract: 'Read info from Zoom 5341 cable modem'
author:
  - 'Matthew Fuller <fullermd@over-yonder.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-CableModem-Zoom5341
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: '0'
version: '1.10'
